<div class="popup">
    <div class="acrylic-bg p-sm" style=" display: flex; flex-direction: column; gap: 0.2em">
        <span class="btn-close btn-highlight" onclick="closePopup()"></span>
        <div id="tnc">
            <h1>Terms and Condition</h1>
            <hr>
            <div class="p-sm" style="display: grid; gap: 1em">
                <h3>Introduction</h3>
                <p>Welcome to <strong>Philadelphia Christ center Fellowship</strong>. By accessing or using this website and its medical services platform, you agree to comply with and be bound by these Terms and Conditions.</p>
                <p>These Terms apply to all users, including patients, clinic staff, administrators, doctors, nurses, and other authorized personnel using the system.</p>
                <p>If you do not agree with any part of these Terms, you must discontinue use of the platform immediately.</p>
                <h3>Purpose of the Platform</h3>
                <p>This platform is designed to:</p>
                <ul style="list-style-type: disc; padding:0 1em">
                    <li>Manage clinic operations</li>
                    <li>Store and process patient medical records</li>
                    <li>Assist in generating preliminary diagnoses</li>
                    <li>Provide prescription management</li>
                    <li>Facilitate appointment scheduling</li>
                </ul>
                <p>The platform is intended solely for lawful medical and administrative purposes.</p>
                <h3>Medical Disclaimer</h3>
                <p>The information, diagnoses, recommendations, and prescriptions generated by the system are intended only to support medical professionals and clinic operations.</p>
                <p>The platform does not replace professional medical judgment, emergency services, or direct consultation with licensed healthcare providers.</p>
                <p>Patients are advised to seek immediate medical attention for emergencies or severe symptoms.</p>
                <h3>User Registration</h3>
                <h4>Staff Account</h4>
                <p>Staff registration is restricted to authorized personnel approved by clinic administration.</p>
                <p>Users registering as staff members agree to:</p>
                <ul style="list-style-type: disc; padding:0 1em">
                    <li>Provide accurate and truthful information</li>
                    <li>Maintain confidentiality of login credentials</li>
                    <li>Use the platform only for authorized medical purposes</li>
                    <li>Protect patient privacy and confidential records</li>
                    <li>Comply with applicable healthcare laws and regulations</li>
                </ul>
                <p>Unauthorized sharing of accounts is strictly prohibited.</p>
                <h4>Patient Accounts</h4>
                <p>Patients using the platform agree to:</p>
                <ul style="list-style-type: disc; padding:0 1em">
                    <li>Provide accurate medical and personal information</li>
                    <li>Keep account credentials secure</li>
                    <li>Use the platform responsibly and lawfully</li>
                    <li>Understand that online assessments may not always be fully accurate</li>
                </ul>
                <p>False or misleading medical information may affect the accuracy of assessments and recommendations.</p>
                <h3>Collection and Use of Data</h3>
                <p>The platform may collect and process the following information:</p>
                <ul style="list-style-type: disc; padding:0 1em">
                    <li>Personal identification details</li>
                    <li>Contact information</li>
                    <li>Medical history</li>
                    <li>Sympotoms and diagnoses</li>
                    <li>Appointment information</li>
                </ul>
                <p>Collected data is used solely for:</p>
                <ul style="list-style-type: disc; padding:0 1em">
                    <li>Medical assessment and treatment</li>
                    <li>Clinic administration</li>
                    <li>Record keeping</li>
                    <li>Improving healthcare services</li>
                    <li>Legal and regulatory compliance</li>
                </ul>
                <p>The clinic will take reasonable measures to protect patient and user data from unauthorized access, disclosure, or misuse.</p>
                <h3>Privacy and Confidentiality</h3>
                <p>All patient records and medical information are treated as confidential.</p>
                <p>Authorized staff members must not:</p>
                <ul style="list-style-type: disc; padding:0 1em">
                    <li>Access records unrelated to their duties</li>
                    <li>Share patient information without authorization</li>
                    <li>Download or distribute confidential records improperly</li>
                </ul>
                <p>Violation of confidentiality policies may result in account termination, disciplinary action, or legal consequences.</p>
                <h3>Staff Responsibilities</h3>
                <p>Clinic staff users agree to:</p>
                <ul style="list-style-type: disc; padding:0 1em">
                    <li>Maintain professional conduct</li>
                    <li>Use accurate medical information</li>
                    <li>Avoid misuse of prescriptions or diagnoses</li>
                    <li>Protect patient safety and confidentiality</li>
                    <li>Report suspicious or unauthorized system activity</li>
                </ul>
                <p>Any misuse of the platform may result in suspension or permanent removal of access privileges.</p>
                <h3>Prescription and Diagnosis Limitations</h3>
                <p>Prescriptions and diagnoses generated through the platform should always be reviewed and verified by qualified healthcare professionals.</p>
                <p>The clinic is not liable for:</p>
                <ul style="list-style-type: disc; padding:0 1em">
                    <li>Incorrect of prescription</li>
                    <li>Misuse of prescription</li>
                    <li>Failure to seek emergency medical care</li>
                    <li>Technical interruptions affecting medical assessments</li>
                </ul>
                <h3>Account Security</h3>
                <p>Users are responsible for safeguarding their usernames and passwords.</p>
                <p>The clinic reserves the right to suspend or terminate accounts involved in:</p>
                <ul style="list-style-type: disc; padding:0 1em">
                    <li>Unauthorized access attempts</li>
                    <li>Fraudulent activity</li>
                    <li>Abuse of medical data</li>
                    <li>Violations of these Terms</li>
                </ul>
                <h3>System Availability</h3>
                <p>While reasonable efforts are made to maintain system availability, the clinic does not guarantee uninterrupted or error-free operation.</p>
                <p>The platform may undergo maintenance, updates, or temporary downtime without prior notice.</p>
                <h3>Prohibited Activities</h3>
                <p>Users may not:</p>
                <ul style="list-style-type: disc; padding:0 1em">
                    <li>Attempts to hack or disrupt the platform</li>
                    <li>Access unauthorized patient data</li>
                    <li>Upload malicious software</li>
                    <li>Use the platform for unlawful purposes</li>
                    <li>Falsify medical records or prescriptions</li>
                </ul>
                <p>Violations may lead to legal action and account termination.</p>
                <h3>Data Retention</h3>
                <p>Medical and account records may be retained in accordance with applicable healthcare laws, regulations, and clinic policies.</p>
                <h3>Amendments</h3>
                <p>The clinic reserves the right to modify these Terms and Conditions at any time.</p>
                <p>Continued use of the platform after changes are posted constitutes acceptance of the updated Terms.</p>
                <h3>Termination of Access</h3>
                <p>The clinic may suspend or terminate user access for:</p>
                <ul style="list-style-type: disc; padding:0 1em">
                    <li>Violations of these Terms</li>
                    <li>Security concerns</li>
                    <li>Misconduct or abuse</li>
                    <li>Unauthorized medical activity</li>
                </ul>
                <h3>Governing Law</h3>
                <p>These Terms and Conditions shall be governed by and interpreted in accordance with the laws applicable in the jurisdiction where the clinic operates.</p>
                <h3>Contact Information</h3>
                <p>For concerns regarding these Terms, privacy, or medical records, please contact:</p>
                <ul>
                    <li><strong>Philadelphia Christcenter Fellowship</strong></li>
                    <li># 26 Lunas Street, Quezon City, Philippines, 1114</li>
                    <li>pcfmainchurch@gmail.com</li>
                </ul>
                <p>By registering or using this platform, you acknowledge that you have read, understood, and agreed to these Terms and Conditions.</p>
            </div>
        </div>
    </div>
</div>